wandb_version: 1

dataset:
  desc: null
  value:
    type: classification
    simple_cls:
      _target_: datasets.prot.swissprot.SPSimpleDataset
    set_cls:
      n_way: 5
      n_support: 5
      n_query: 15
      _target_: datasets.prot.swissprot.SPSetDataset
    name: swissprot
eval_split:
  desc: null
  value:
  - train
  - val
  - test
backbone:
  desc: null
  value:
    _target_: backbones.fcnet.FCNet
    layer_dim:
    - 512
    - 512
train_classes:
  desc: null
  value: 7195
n_way:
  desc: null
  value: 5
n_shot:
  desc: null
  value: 5
n_query:
  desc: null
  value: 15
method:
  desc: null
  value:
    name: relationnet
    train_batch: null
    val_batch: null
    fast_weight: false
    start_epoch: 0
    eval_type: set
    stop_epoch: 60
    type: meta
    cls:
      n_way: 5
      n_support: 5
      _target_: methods.relationnet.RelationNet
model:
  desc: null
  value: FCNet
mode:
  desc: null
  value: train
exp:
  desc: null
  value:
    name: testonmps
    save_freq: 10
    resume: false
    seed: 42
    val_freq: 1
optimizer:
  desc: null
  value: Adam
lr:
  desc: null
  value: 0.001
optimizer_cls:
  desc: null
  value:
    _target_: torch.optim.Adam
    lr: 0.001
checkpoint:
  desc: null
  value:
    dir: checkpoints/testonmps/swissprot/relationnet_FCNet
    test_iter: best_model
    time: '20231212_222609'
wandb:
  desc: null
  value:
    project: fewshotbench
    entity: dl4bm
    mode: online
iter_num:
  desc: null
  value: 600
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702416370.538291
    t:
      1:
      - 1
      - 5
      - 41
      - 50
      - 51
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 41
      - 50
      - 51
      - 53
      - 55
      - 77
      3:
      - 7
      - 16
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 4
      - 8
    m:
    - 1: epoch
      4: epoch
      6:
      - 1
    - 1: loss
      5: 1
      6:
      - 1
    - 1: acc/val
      5: 1
      6:
      - 1
model_details:
  desc: null
  value:
    feature:
      encoder:
        '0':
          '0': Linear(in_features=1280, out_features=512, bias=True)
          '1': BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          '2': ReLU()
          '3': Dropout(p=0.2, inplace=False)
        '1':
          '0': Linear(in_features=512, out_features=512, bias=True)
          '1': BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          '2': ReLU()
          '3': Dropout(p=0.2, inplace=False)
    loss_fn: CrossEntropyLoss()
    relation_module:
      layer1:
        '0': Linear(in_features=1024, out_features=512, bias=True)
        '1': BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        '2': ReLU()
        '3': Dropout(p=0.4, inplace=False)
      layer2:
        '0': Linear(in_features=512, out_features=512, bias=True)
        '1': BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        '2': ReLU()
        '3': Dropout(p=0.4, inplace=False)
      layer3: Linear(in_features=512, out_features=1, bias=True)
      sigmoid: Sigmoid()
optimizer_details:
  desc: null
  value:
    lr: 0.001
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0
    amsgrad: false
    maximize: false
    foreach: null
    capturable: false
    differentiable: false
    fused: null
